---
title: Cytokine Networks Reveal Pathogenic Mechanisms and Therapeutic Targets in Ulcerative
  Colitis
output: html_document
date: "2024-07-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=FALSE}
# load necessary packages
library(tidyverse)
library(ggraph)
library(tidygraph)
library(igraph)
library(ggthemes)
library(patchwork)
library(ggrepel)
library(rstatix)
library(ggthemes)
#load networks
comp<-readRDS('cci_n.rds') |> bind_rows() 
```

The plots aren't necessary in the same order as they appear in the manuscript, but rather how they were generated.

```{r}
# using the Cui et al supplementary data to validate cytokine networks: https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-023-06816-9/MediaObjects/41586_2023_6816_MOESM5_ESM.xlsx
cklcyts <- c(comp$source, comp$target) |> unique()

#S3 from supplementary files of Cui et al
library(readxl)    
path <- "41586_2023_6816_MOESM5_ESM.xlsx"
S3<-path %>% 
  excel_sheets() %>% 
  set_names() %>% 
  map(read_excel, path = path)
S3df <- bind_rows(S3)

# converting symbols
library(nichenetr)
S3_hmn<-nichenetr::convert_mouse_to_human_symbols(unique(S3df$Gene))
S3_human_names <- data.frame(as.list(S3_hmn)) |> t() |> as.data.frame() |> rownames_to_column('mouse')
S3_df_human<-S3df |> left_join(S3_human_names, by=c('Gene'='mouse'))
S3_df_human_cyttargets<-S3_df_human |> dplyr::filter(V1 %in% cklcyts)

#harmonising names
S3_df_human_cyttargets<- S3_df_human_cyttargets |> mutate(Cytokine = str_replace(Cytokine,pattern = '-', replacement = ''))
S3_df_human_cyttargets_gs<-S3_df_human_cyttargets |> mutate(Cytokine_GS = case_when(
  Cytokine == "IFNα1" ~ "IFNA1",
  Cytokine == "IFNβ" ~ "IFNB",
  Cytokine == "IFNκ" ~ "IFNK",
  Cytokine == "IFNγ" ~ "IFNG",
  Cytokine == "IL1α" ~ "IL1A",
  Cytokine == "IL1β" ~ "IL1B",
  Cytokine == "GMCSF" ~ "CSF2",
  Cytokine == "TNFα" ~ "TNF",
  Cytokine == "CD40L" ~ "CD40LG",
  Cytokine == "TL1A" ~ "TNFSF15",
  Cytokine == "IL12" ~ "IL12A",
  Cytokine == "CD30L" ~ "TNFSF8",
  Cytokine == "BAFF" ~ "TNFSF13B",
  Cytokine == "MCSF" ~ "CSF1",
  Cytokine == "RANKL" ~ "TNFSF11",
  Cytokine == "TGFβ1" ~ "TGFB1",
  Cytokine == "GCSF" ~ "CSF3",
  Cytokine == "IL23" ~ "IL23A",
  Cytokine == "IL36α" ~ "IL36A",
  Cytokine == "LTα1/β2" ~ "LTA1/B2",
  Cytokine == "APRIL" ~ "TNFSF13",
  Cytokine == "AdipoQ" ~ "ADIPOQ",
  Cytokine == "ADSF" ~ "RETN",
  Cytokine == "CD27L" ~ "CD70",
  Cytokine == "FasL" ~ "FASLG",
  Cytokine == "IFNλ2" ~ "IFNG2",
  Cytokine == "FGFβ" ~ "FGF2",
  Cytokine == "IFNε" ~ "IFNE",
  Cytokine == "IL1Ra" ~ "IL1R1",
  Cytokine == "IL36α" ~ "IL36A",
  Cytokine == "Noggin" ~ "NOG",
  Cytokine == "TRAIL" ~ "TNFSF10",
  Cytokine == "TWEAK" ~ "TNFSF12",
  Cytokine == "Leptin" ~ "LEP",
  Cytokine == "LIGHT" ~ "TNFSF14",
  Cytokine == "Decorin" ~ "DCN",
  Cytokine == "CT1" ~ "CTF1,",
  Cytokine == "IL36Ra" ~ "IL36RN",
  Cytokine == "LTα2/β1" ~ "LTA2/B1",
  Cytokine == "NP" ~ "CTF2P",
  Cytokine == "C5a" ~ "C5",
  Cytokine == "C3a" ~ "C3",
  TRUE ~ as.character(Cytokine)
))

testOverlaps <- function(dataset) {
  matchingUpstreamCyt <- unique(intersect(S3_df_human_cyttargets_gs$Cytokine_GS, dataset$source))
  print(length(matchingUpstreamCyt))
  st <- dataset$state |> unique()
  print(st)
  results <- list()
  
  for (i in matchingUpstreamCyt) {
    cs <- unique(pull(filter(S3_df_human_cyttargets_gs, Cytokine_GS == paste0(i)), V1))
    indata <- unique(pull(filter(dataset, source == paste0(i)), target))
    overlap <- intersect(cs, indata)
    all_genes <- unique(c(S3_df_human_cyttargets_gs$Cytokine_GS, S3_df_human_cyttargets_gs$V1, dataset$source, dataset$target))
    state <- dataset |> pull(state) |> unique()
    bothSets <- union(cs, indata)
    overlap <- intersect(cs, indata)
    jaccard <- length(overlap) / length(bothSets)
    
    q <- length(intersect(cs, indata))
    m <- length(cs)
    n <- length(all_genes) - m
    k <- length(indata)
    p_value <- phyper(q, m, n, k, lower.tail = F)
    out <- data.frame(
      disease_state = paste0(state),
      cytokine = paste0(i),
      p_value_overlap = p_value,
      jaccard_overlap = jaccard,
      overlapping_cytokine_targets = q,
      targets_of_cytokine_in_paper = m,
      targets_of_cytokine_in_RNAseq = k
    )
    #ignore if no overlap
    #out<-out |> dplyr::filter(overlapping_cytokine_targets > 0)
    results[[paste0(i)]] <- out
  }
  return(bind_rows(results))
}
ucinf<-comp |> dplyr::filter(state=='UC_inflamed_treated')
ucinfn<-comp |> dplyr::filter(state=='UC_inflamed_naive')
ucninf<-comp |> dplyr::filter(state=='UC_noninflamed_treated')
h<-comp |> dplyr::filter(state=='healthy')
res <- list(ucinf, ucinfn,ucninf,h)
resout<-lapply(res, testOverlaps)

#results
resall<-bind_rows(resout)
sigres<-resall |> mutate(adjp = p.adjust(p_value_overlap, method = 'fdr')) |> dplyr::filter(adjp <= 0.05)
#sign. cytokines
sigcyt <- sigres$cytokine |> unique()

# rename TNFSF15 with TL1A for the plot
sigres_name_fix <- sigres %>% mutate(cytokine = case_when(
  cytokine == 'TNFSF15' ~ 'TL1A',
  TRUE ~ as.character(cytokine)
))

# Figure 2A
state_order <- c("healthy","UC_inflamed_treated",'UC_noninflamed_treated',"UC_inflamed_naive")

ggplot(sigres_name_fix,aes(x=cytokine, y=factor(disease_state, level = state_order), fill= adjp)) + 
  geom_tile(color = "white",
            lwd = 1.5,
            linetype = 1, )+
  geom_point(aes(size = jaccard_overlap))+
  coord_fixed()+
  scale_y_discrete(limits=c("healthy","UC_inflamed_naive","UC_inflamed_treated",'UC_noninflamed_treated'))+
  scale_x_discrete(position = 'top')+
  scale_fill_gradient(low = "#FEB800", high = "white") +
  theme_hc()+ 
  theme(text = element_text(family="helvetica", size=14),
        axis.ticks.y=element_blank(),
        axis.text.x=element_text(angle = 45, hjust = 0, size=14), 
        panel.border = element_blank())+
  xlab('Cytokine network')+
  ylab('Cytokine')+
  labs(fill = 'FDR', size = 'Jaccard-index')+ theme(legend.text=element_text(size=8))
```

```{r, echo=FALSE}
# Figure 2B: organoid comparison
all_celltypes<- c(inf$source_cell, inf$target_cell) |> unique()
organoid_celltypes <- c('Goblet', 'Enterocyte', 'Cycling TA', 'TA', 'Enteroendocrine', "Adult colonocyte", "Pediatric colonocyte", "BEST4+ epithelial")

inf<-comp |> dplyr::filter(state == 'UC_inflamed_treated') |> 
  separate_rows(cells, sep = ",") |>
  separate(cells, sep = ":", into = c("source_cell", "target_cell"))
organoid_inf<- inf |> dplyr::filter(target_cell %in% organoid_celltypes) |> dplyr::filter( source == 'TNF') |> group_by(target,target_cell) |> tally()
ifngTargets<-organoid_inf |> pull(target) |> unique()
df <- read_csv('Condition_Inflamed non-treated_Inflamed treated with IFNg_sig_genes.csv')
ids <- clusterProfiler::bitr(df$gene, fromType="ENSEMBL", toType="SYMBOL", OrgDb="org.Hs.eg.db")
dfGn <- df |> left_join(ids, by=c('gene'='ENSEMBL'))|> dplyr::filter(SYMBOL %in% allcyt) |> dplyr::filter(abs(log2FoldChange) >= 2) |> dplyr::filter(SYMBOL %in% allcyt)
cklOrganoidOverlap <- dfGn |> dplyr::filter(SYMBOL %in% ifngTargets)

noninf <-comp |> dplyr::filter(state == 'UC_noninflamed_treated') |> 
  separate_rows(cells, sep = ",") |>
  separate(cells, sep = ":", into = c("source_cell", "target_cell"))
organoid_noninf<- noninf |> dplyr::filter(target_cell %in% organoid_celltypes & source == 'IFNG') |> group_by(target,target_cell) |> tally()
ifngTargets_noninf<-organoid_noninf |> pull(target) |> unique()
df2<-read_csv('Condition_Non-inflamed non-treated_Non-inflamed treated with  IFNg_sig_genes.csv')
ids2 <- clusterProfiler::bitr(df2$gene, fromType="ENSEMBL", toType="SYMBOL", OrgDb="org.Hs.eg.db")
dfGn2 <- df2 |> left_join(ids2, by=c('gene'='ENSEMBL')) |> dplyr::filter(abs(log2FoldChange) >= 2)|> dplyr::filter(SYMBOL %in% allcyt)
cklOrganoidOverlap_noninflamed <- dfGn2 |> dplyr::filter(SYMBOL %in% ifngTargets_noninf)

#inf
q <- length(intersect(dfGn$SYMBOL, ifngTargets)) |> as.numeric()
m <- length(dfGn$SYMBOL)|> as.numeric()
n <- (length(allcyt) - m)|> as.numeric()
k <- length(ifngTargets)|> as.numeric()
p_value <- phyper(q, m, n, k, lower.tail = F) # 0.005
bothSets <- union(dfGn$SYMBOL, ifngTargets)
overlap <- intersect(dfGn$SYMBOL, ifngTargets)
jaccard <- length(overlap) / length(bothSets) # 0.10

#noninf
q <- length(intersect(dfGn2$SYMBOL, ifngTargets_noninf)) |> as.numeric()
m <- length(dfGn2$SYMBOL)|> as.numeric()
n <- (length(allcyt) - m)|> as.numeric()
k <- length(ifngTargets_noninf)|> as.numeric()
p_value <- phyper(q, m, n, k, lower.tail = F) # 0.0004
bothSets <- union(dfGn2$SYMBOL, ifngTargets_noninf)
overlap <- intersect(dfGn2$SYMBOL, ifngTargets_noninf)
jaccard <- length(overlap) / length(bothSets) #0.13
```



```{r, echo=FALSE}
# Fig 1B, 1C, Fig 1D

#net characteristics
sgrsstate <- sigres$disease_state |> unique()
no_edges <- comp |> group_by(state) |> tally()
no_edges$type <- 'Cytokine-cytokine interactions'
no_nodes<-comp |> group_by(state) |> summarise( n = length(unique(c(source, target))))
no_nodes$type <- 'Cytokines'
netdat<-rbind(no_edges, no_nodes) |> dplyr::filter(state %in% sgrsstate)

pnet<-ggplot(netdat, aes(x=n, y = state))+
  geom_point(aes(shape=type), color = '#8CC7C6', fill='#8CC7C6', size=5)+
  #scale_color_manual(values = c('#8CC7C6','#7184af'), breaks = c('Cytokines', 'Cytokine-cytokine interactions'))+
  scale_shape_manual(values = c('Cytokines' = 21, 'Cytokine-cytokine interactions' =  24), breaks = c('Cytokines', 'Cytokine-cytokine interactions'))+
  scale_y_discrete(limits=c("UC_inflamed_naive",'UC_noninflamed_treated',"UC_inflamed_treated", "healthy"))+ 
  theme_hc(base_size = 18)+
  theme(axis.ticks.y=element_blank(),panel.border = element_blank(),legend.title=element_blank(),aspect.ratio = 0.7)+
  xlim(0,475)+
  xlab(' ')+
  ylab(' ')
pnet

naivenet<-comp |> dplyr::group_by(source,target) |> tally()|> dplyr::rename(states = n) 
pcytnet2<-naivenet |> as_tbl_graph() |> activate(nodes) |> mutate(Degree = centrality_degree(mode = 'all'), btw = centrality_betweenness(), labelName = case_when(
  name %in% sigcyt ~ as.character(name),
  TRUE ~ ' '
)) |> 
  ggraph(layout = "centrality", cent = btw) +  
  geom_edge_link(color = '#8CC7C6',arrow = arrow(type = "closed", length = unit(2, "mm")), start_cap = circle(3, 'mm'), end_cap = circle(5, "mm"), width =0.7, alpha = 0.4) +
  geom_node_point(aes(size = Degree), fill = '#8CC7C6', shape=21, show.legend = T) +
  scale_size_continuous(range = c(2, 14)) +
  geom_node_text(aes(filter = (Degree > 15),label = name),  fontface = 'bold',size = 5, repel = F, nudge_y = -5, show.legend = F) +
  theme_graph(base_size = 26)+ theme(strip.text = element_text(size = 20),text=element_text(family="Helvetica")) + theme(legend.position = 'bottom')
pcytnet2

# top degree lollipop
degs<-naivenet |> as_tbl_graph() |> activate(nodes) |> mutate(degree = centrality_degree(mode = 'all')) |> as_tibble() |> arrange(-degree) |> head(10)
degplot<-ggplot(degs, aes(x=reorder(name, degree), y=degree)) +
  geom_segment( aes(x=reorder(name, degree), xend=reorder(name, degree), y=0, yend=degree), color="grey80") +
  geom_point( color="#8CC7C6",size=5) +
  theme_light() +
  coord_flip() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  )+
  theme_hc(base_size = 16)+
  xlab('Cytokine')+
  ylab('Degree')
degplot
```

```{r}
# Fig2A

# edge weight fold change calculation
cc_wide <- comp |> 
  dplyr::select(source, target, state, weight) |>
  pivot_wider(names_from = state, values_from = c(weight)) |>
  mutate_all(funs(replace_na(., 0)))

cc_wide_FC <- cc_wide |> mutate(
  uc_inflamed_naive_FC = log2(UC_inflamed_naive / healthy),
  uc_inflamed_treated_FC = log2(UC_inflamed_treated / healthy),
  uc_noninflamed_treated_FC = log2(UC_noninflamed_treated / healthy),
  #cd_inflamed_treated_FC = log2(CD_inflamed_treated / healthy),
  #cd_noninflamed_treated_FC = log2(CD_noninflamed_treated / healthy),
  healthy_FC = 0
)

cc_long_FC <- cc_wide_FC |>
  pivot_longer(cols = uc_inflamed_naive_FC:healthy_FC, names_to = "state", values_to = "logFC") |> mutate(logFC = case_when(
    is.nan(logFC) ~ 0,
    TRUE ~ as.numeric(logFC)
  ))

cc_long_FC<-cc_long_FC |> select(-contains('st_')) #|> filter(logFC != 0)

hfc <- cc_long_FC |> filter(state == 'healthy_FC') |> filter(healthy != 0 & logFC == 0)

fc2 <- cc_long_FC |> filter(state != 'healthy_FC') |> filter(logFC != 0) |> mutate(logFC = case_when(logFC == Inf ~ 15,
                                                                   logFC == -Inf ~ -15,
                                                                   TRUE ~ as.numeric(logFC)))
fc2<-rbind(fc2, hfc)

cellcomp<-comp |> separate_rows(cells,sep = ',') |> separate(cells, into = c('source_cell','target_cell'), sep=':')

#for all ints
cellcompint <- cellcomp |> tidyr::unite(interaction, c(source,target), sep = '_')
ints <- cellcompint$interaction |> unique()
results <- list()
for (i in ints){
  uc_i1 <- cellcompint |>filter(interaction == paste0(i) & state == 'UC_inflamed_naive') |> pull(source_cell) |> unique() 
  uc_i2 <- cellcompint |>filter(interaction == paste0(i) & state == 'UC_inflamed_naive') |> pull(target_cell) |> unique() 
  hc_i1  <- cellcompint |>filter(interaction == paste0(i) & state == 'healthy') |> pull(source_cell) |> unique() 
  hc_i2  <- cellcompint |>filter(interaction == paste0(i) & state == 'healthy') |> pull(target_cell) |> unique() 
  uc_i <- unique(c(uc_i1,uc_i2))
  hc_i <- unique(c(hc_i1,hc_i2))
  jc <-length(intersect(uc_i,hc_i)) / length(union(uc_i,hc_i))
  uc_specific_cells <- setdiff(uc_i, hc_i)
  health_specific_cells <- setdiff(uc_i, hc_i)
  shared_cells <- intersect(uc_i, hc_i)
  results[[paste0(i)]] <- jc
}

results1 <- list()
for (i in ints){
  uc_i1 <- cellcompint |>filter(interaction == paste0(i) & state == 'UC_inflamed_treated') |> pull(source_cell) |> unique() 
  uc_i2 <- cellcompint |>filter(interaction == paste0(i) & state == 'UC_inflamed_treated') |> pull(target_cell) |> unique() 
  hc_i1  <- cellcompint |>filter(interaction == paste0(i) & state == 'healthy') |> pull(source_cell) |> unique() 
  hc_i2  <- cellcompint |>filter(interaction == paste0(i) & state == 'healthy') |> pull(target_cell) |> unique() 
  uc_i <- unique(c(uc_i1,uc_i2))
  hc_i <- unique(c(hc_i1,hc_i2))
  jc <-length(intersect(uc_i,hc_i)) / length(union(uc_i,hc_i))
  uc_specific_cells <- setdiff(uc_i, hc_i)
  health_specific_cells <- setdiff(uc_i, hc_i)
  shared_cells <- intersect(uc_i, hc_i)
  results1[[paste0(i)]] <- jc
}

results2 <- list()
for (i in ints){
  uc_i1 <- cellcompint |>filter(interaction == paste0(i) & state == 'UC_noninflamed_treated') |> pull(source_cell) |> unique() 
  uc_i2 <- cellcompint |>filter(interaction == paste0(i) & state == 'UC_noninflamed_treated') |> pull(target_cell) |> unique() 
  hc_i1  <- cellcompint |>filter(interaction == paste0(i) & state == 'healthy') |> pull(source_cell) |> unique() 
  hc_i2  <- cellcompint |>filter(interaction == paste0(i) & state == 'healthy') |> pull(target_cell) |> unique() 
  uc_i <- unique(c(uc_i1,uc_i2))
  hc_i <- unique(c(hc_i1,hc_i2))
  jc <-length(intersect(uc_i,hc_i)) / length(union(uc_i,hc_i))
  uc_specific_cells <- setdiff(uc_i, hc_i)
  health_specific_cells <- setdiff(uc_i, hc_i)
  shared_cells <- intersect(uc_i, hc_i)
  results2[[paste0(i)]] <- jc
}

#list to jc
jc_naive_healthy <- bind_rows(results) |> t() |> as.data.frame() |> rownames_to_column('interaction') |> dplyr::rename(Jaccard = V1)
compjc <-jc_naive_healthy |> separate(interaction, into = c('source','target'))
comp_uc_h_jaccard<- fc2 |> dplyr::filter(state == 'uc_inflamed_naive_FC') |> left_join(compjc) |> write_tsv('naive_jaccard_fc.tsv')

jc_inflamed_healthy <- bind_rows(results1) |> t() |> as.data.frame() |> rownames_to_column('interaction') |> dplyr::rename(Jaccard = V1)
compjci <-jc_inflamed_healthy |> separate(interaction, into = c('source','target'))
comp_uci_h_jaccard<- fc2 |> dplyr::filter(state == 'uc_inflamed_treated_FC') |> left_join(compjci) |> write_tsv('inflamed_jaccard_fc.tsv')

jc_noninflamed_healthy <- bind_rows(results2) |> t() |> as.data.frame() |> rownames_to_column('interaction') |> dplyr::rename(Jaccard = V1)
compjcni <-jc_noninflamed_healthy |> separate(interaction, into = c('source','target'))
comp_ucni_h_jaccard<- fc2 |> dplyr::filter(state == 'uc_noninflamed_treated_FC') |> left_join(compjcni) |> write_tsv('noninflamed_jaccard_fc.tsv')

jaccard_comps <- rbind(comp_uc_h_jaccard, comp_uci_h_jaccard, comp_ucni_h_jaccard) |> unique()

trt <- jaccard_comps |> filter(state == 'uc_inflamed_naive_FC' | state == 'uc_inflamed_treated_FC') |> mutate(state = if_else(state == 'uc_inflamed_naive_FC', 'UC_inflamed_naive', 'UC_inflamed_treated')) 

trt|> ggplot(aes(x = state, y= Jaccard))+
  ggdist::stat_halfeye(
    aes(fill = state),
    adjust = .5, 
    width = .6, 
    .width = 0, 
    justification = -.2, 
    point_colour = NA  ) + 
    scale_fill_manual(values = c('UC_inflamed_naive' = '#FE6100', 'UC_inflamed_treated'='#DC267F'))+
  geom_boxplot(
    width = .15, 
    outlier.shape = NA
  ) +
  ## add justified jitter from the {gghalves} package
  gghalves::geom_half_point(
    ## draw jitter on the left
    side = "l", 
    ## control range of jitter
    range_scale = .4, 
    ## add some transparency
    alpha = .2
  )+
  theme_hc(base_size = 18)+ theme(legend.position = "none")+xlab('Cytokine network')+ylab('Jaccard index')

ks_naive <- trt |> filter(state == 'UC_inflamed_naive') |> pull(Jaccard)
ks_treated <- trt |> filter(state == 'UC_inflamed_treated') |> pull(Jaccard)
wilcox.test(ks_naive,ks_treated)
trt |> group_by(state) |> summarise(medjac = median(Jaccard))
```

```{r}
# Fig 2B
naive <- comp |> filter(state == 'UC_inflamed_naive')
treated <- comp |> filter(state == 'UC_inflamed_treated')
compare_state <- function(ingraph1, ingraph2){
  nv <- ingraph1 |> as_tbl_graph() |> activate(nodes) |> mutate(degree = centrality_degree(mode='all'),
                                                                                                     betweenness = centrality_betweenness(directed = T)) |> as_tibble()
  tr <- ingraph2  |> as_tbl_graph() |> activate(nodes) |> mutate(degree = centrality_degree(mode='all'),
                                                                    betweenness = centrality_betweenness(directed = T)) |> as_tibble()
  compare <- nv |> left_join(tr, by = 'name', suffix = c('_naive','_treated')) |> mutate(
    deltaDegree = abs(degree_naive - degree_treated),
    deltaBtw = abs(betweenness_naive - betweenness_treated)
  )|> arrange(-deltaDegree)
  return(compare)
}
deltas <- compare_state(naive, treated)

ddeg <- deltas |> select(name, degree_naive,degree_treated,deltaDegree)
dbts <- deltas |> select(name,betweenness_naive,betweenness_treated, deltaBtw)

library(ggradar)
topdeg <- ddeg |> arrange(-deltaDegree) |> head(10) |> pull(name)

ddd<-ddeg |> select(-deltaDegree) |> filter(name %in% topdeg) |> column_to_rownames('name') |> t() |> as.data.frame() |> as_tibble(rownames = "group")

degradar<-ggradar(ddd,
        values.radar = c(0, 30, 60),
        grid.min=0, grid.mid = 30, grid.max = 60, group.line.width = 0.5, 
        group.point.size = 1.25, fill = T,
            fill.alpha = 0.8,
            plot.legend = F)+
  scale_color_manual(values = c('#FE6100','#DC267F'))+
  scale_fill_manual(values = c('#FE6100','#DC267F'))+
  xlab('Degree')


topbtw <- dbts |> arrange(-deltaBtw) |> head(10) |> pull(name)

bbb<-dbts |> select(-deltaBtw) |> filter(name %in% topbtw) |> column_to_rownames('name') |> t() |> as.data.frame() |> as_tibble(rownames = "group")

degbtw<-ggradar(bbb,
        values.radar = c(0, 340, 675),
        grid.min=0, grid.mid = 340, grid.max = 675, group.line.width = 0.5, 
        group.point.size = 1.25, fill = T,
            fill.alpha = 0.8,
            plot.legend = F)+
  scale_color_manual(values = c('#FE6100','#DC267F'))+
  scale_fill_manual(values = c('#FE6100','#DC267F'))+
  xlab('Betweenness centrality')


```

```{r}
#Interactions completely unique to UC naive
library(ggupset)
ibd_upset <- comp |> filter(state == 'UC_noninflamed_treated' |state == 'UC_inflamed_treated' | state == 'UC_inflamed_naive' | state == 'healthy') |> 
  tidyr::unite("interaction", c(source, target), sep = "_") |>
  dplyr::select(interaction, state)

ups<-ibd_upset |>
  group_by(interaction) |>
  summarise(states = list(state)) |>
  ggplot(aes(x = states)) +
  geom_text(stat = "count", aes(label = after_stat(count)), vjust = -1) +
  scale_x_upset(order_by = "freq")+labs(
    title = 'Overlapping CCI network interactions',n_intersections = 20,
    n_sets = 5
  )+
  ylab('Overlap size')+
  theme_hc(base_size=16)


U <- ups[["data"]] |>as.data.frame()
U$states <- str_replace_all(U$states, 'c\\(\\"','') 
U$states <- str_replace_all(U$states, '\\"\\, \\"',',') 
U$states <- str_replace_all(U$states, '\\"\\)','') 

naive_unique_network<- U |> filter(states == 'UC_inflamed_naive') |> separate(interaction, into = c('source','target'), sep='_') |> dplyr::rename(state = states)
naive_unique_network$edge_status <- 'unique'

indeg_uc_naive<-naive_unique_network |> as_tbl_graph() |> activate(nodes) |> mutate(degree = centrality_degree(mode='in')) |> as_tibble() |> arrange(-degree) |> head(5)

top_naive_nodes_plot<-ggplot(indeg_uc_naive, aes(x=reorder(name, degree), y=degree)) +
  geom_bar(stat = 'identity',fill="#FE6100", width=0.85) +
  coord_flip() +
    theme_light() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  )+
  xlab('Cytokine')+
  ylab('Incoming interactions')
top_naive_nodes_plot

outdeg_uc_naive<-naive_unique_network |> as_tbl_graph() |> activate(nodes) |> mutate(degree = centrality_degree(mode='out')) |> as_tibble() |> arrange(-degree) |> head(5)

top_naive_nodes_plot_out<-ggplot(outdeg_uc_naive, aes(x=reorder(name, degree), y=degree)) +
   geom_bar(stat = 'identity',fill="#FE6100", width=0.85) +
  coord_flip() +
  theme(
    panel.background = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  )+
  xlab('Cytokine')+
  ylab('Outgoing interactions')
top_naive_nodes_plot_out


```

```{r}
#Fig4B
# rewiring values were created using the DyNet Cytoscape app, using multiple comparison mode. Node rewiring results were exported to structural_rewiring.csv

dncyt<-read_csv('structural_rewiring.csv') |> dplyr::rename(Dn = `DyNet Rewiring (Dn-score)`,Dnc = `Dn-Score (degree corrected)`, degree = `Edge Count`) |> filter(cc_h_weighted.tsv_present == TRUE & cc_uc_inf_weighted.tsv_present == TRUE & cc_uc_naive_weighted.tsv_present == TRUE & cc_uc_ninf_weighted.tsv_present == TRUE) %>% mutate(name = case_when(
  name == 'TNFSF15' ~ 'TL1A',
  TRUE ~ as.character(name)
))
dncyt$scaled_Dnc <- scale(dncyt$Dnc, center = TRUE, scale = TRUE)
topcyt<-dncyt |> arrange(-Dnc) |> head(10) |> pull(name)

str_rew<-dncyt |> arrange(-Dnc) |> head(10) |> ggplot(aes(x=fct_relevel(name, rev(topcyt)),y=scaled_Dnc))+
  geom_point(aes(size=degree), color = 'darkred', fill = 'darkred', shape = 21)+
  scale_size_continuous(range=c(3,9))+
  ylim(0,2)+
  coord_flip()+
  ylab('Degree corrected rewiring score (Z-scaled)')+xlab('Cytokine')+ theme_hc(base_size = 22)+theme(legend.position = 'right')+labs(fill = 'Scaled rewiring\n(degree corrected)')
str_rew

#Fig4A
topnames <- topcyt[1:5]
rewdist<-dncyt |> mutate(labelname = case_when(name %in% topnames ~ as.character(name),
                                       TRUE ~ as.character('')))|> 
  ggplot(aes(x = selected, y= Dnc))+
  ggdist::stat_halfeye(
    fill = '#8CC7C6',
    adjust = .5, 
    width = .6, 
    .width = 0, 
    justification = -.2, 
    point_colour = NA  ) +  geom_boxplot(
    width = .15, 
    outlier.shape = NA
  ) +
  ## add justified jitter from the {gghalves} package
  gghalves::geom_half_point(
    ## draw jitter on the left
    side = "l", 
    ## control range of jitter
    range_scale = .4, 
    ## add some transparency
    alpha = .2
  )+geom_text_repel(aes(label=labelname),size=5, repel=T) +
    theme_hc(base_size = 22)+xlab('Cytokines')+ylab('Rewiring score (degree corrected)')
rewdist
```

```{r}
# load nichenet model
ligand_target_matrix <- readRDS("../rds/ligand_target_matrix_nsga2r_final.rds")
weighted_networks <- readRDS("../rds/weighted_networks_nsga2r_final.rds")
ligand_tf_matrix <- readRDS("../rds/ligand_tf_matrix_nsga2r_final.rds")
networks <- readRDS("../rds/OP_nichenet_networks.RDS")
lr_network <- networks$lr_network %>% dplyr::filter(from %in% colnames(ligand_target_matrix))
lr_network <- dplyr::rename(lr_network, ligand = from, receptor = to)
sig_network <- networks$signaling_network
gr_network <- networks$gr_network

#seurat obj of the inflamed naive scRNA-Seq data
naiverds <- readRDS('../rds/uc_inflamed_naive.rds')
Idents(naiverds)<-'minor_cluster'

## geneset of interest == cytokines
comp<-readRDS('../rds/cci_n.rds') |> bind_rows()  
geneset_oi <-  c(comp$source, comp$target) |> unique()

testcci<-comp |> filter(state == 'UC_inflamed_naive')

jakcci<- testcci |> separate_rows(cells, sep = ',') |> separate(cells, into=c('source_cell','target_cell'), sep=':') |> 
  select(source,target,target_cell) |> distinct()

#target celltypes
target_celltypes <- jakcci$target_cell |> unique()

# listing expressed genes for every celltype to speed up analysis down the line
genelist <- list()

for (j in target_celltypes){
  df <- get_expressed_genes(celltype_oi = paste0(j), naiverds)
  genelist[[paste0(j)]]<-df
}

results <- list()
for (row in 1:nrow(jakcci)){
  src <- jakcci[row, 'source']
  trg <- jakcci[row, 'target']
  tc <- jakcci[row, 'target_cell']
  expgenes_in_cells <- genelist[paste0(tc)] |> unlist() |> unique()
  expgenes_in_cells <- c(expgenes_in_cells, src, trg)
  #filtering weighted network for expressed genes
  wn2 <- list()
  wn2$lr_sig <- weighted_networks$lr_sig |> filter(from %in% expgenes_in_cells & to %in% expgenes_in_cells)
  wn2$gr <- weighted_networks$gr |> filter(from %in% expgenes_in_cells & to %in% expgenes_in_cells)
  
  ligands_all <- src 
  targets_all <- c(paste0(trg))
  
  active_signaling_network <- get_ligand_signaling_path(
    ligand_tf_matrix = ligand_tf_matrix,
    ligands_all = ligands_all,
    targets_all = targets_all,
    weighted_networks = wn2,
    top_n_regulators = 10
  )
  
  el <- rbind(active_signaling_network$sig, active_signaling_network$gr) |> dplyr::select(from, to) |> distinct()
  
  jk1 <- ('JAK1' %in% el$from | 'JAK1' %in% el$to) |> as.logical() |> as.integer()
  jk2 <- ('JAK2' %in% el$from | 'JAK2' %in% el$to) |> as.logical() |> as.integer()
  jk3 <- ('JAK3' %in% el$from | 'JAK3' %in% el$to) |> as.logical() |> as.integer()
  tk2 <- ('TYK2' %in% el$from | 'TYK2' %in% el$to) |> as.logical() |> as.integer()
  
  outdf <- data.frame(src,trg,jk1,jk2,jk3,tk2) |> tibble()
  results[[paste0(src, '_',trg,'_',tc)]] <- outdf
  
}
# per cell data
expjak_cell <- bind_rows(results, .id='id')
expjak_cell$jaks <- rowSums( expjak_cell[,4:7] )
expjak_cell<-expjak_cell |> separate(id, into = c('s','t','cell'), sep='_', extra = 'merge') |> select(-s,-t)

# interactions collapsed for each celltype + presence/absence
per_cell<-expjak_cell |> group_by(source,target,jk1,jk2,jk3,tk2) |> summarise(celltype = paste(cell, collapse=','), n=n())
per_cell$jaks <- rowSums( per_cell[,3:6] )

# keeping only JAK interactions, listing affected celltypes
per_system<-per_cell |> filter(jaks > 0)
uc_jaks<-per_system |> group_by(source,target) |> summarise(jk1=sum(jk1), jk2=sum(jk2), jk3=sum(jk3), tk2=sum(tk2), cells = paste(celltype, collapse = ','))|>  mutate(
  jk1 = ifelse(jk1 > 0, 1, 0),
  jk2 = ifelse(jk2 > 0, 1, 0),
  jk3 = ifelse(jk3 > 0, 1, 0),
  tk2 = ifelse(tk2 > 0, 1, 0)
)

uc_jaks$jaks <- rowSums( uc_jaks[,3:6] )

uc_jaks<-uc_jaks|> dplyr::rename(JAK1 = jk1, JAK2 = jk2, JAK3 = jk3, TYK2 = tk2)

```

```{r}
#Fig5A,5B

jak_usage<-uc_jaks |> select(source, target,jaks) |> group_by(jaks) |> tally()
jak_usage_plot<-ggplot(jak_usage, aes(x=jaks, y=n)) + 
  geom_bar(stat = "identity", fill='lightblue')+
  theme_hc(base_size = 16)+
  coord_flip()+
  scale_x_reverse()+
  ylab('Cytokine-cytokine interactions')+
  xlab('Number of potential JAK proteins used in the interaction')+
  theme(plot.margin = margin(1,1,1.5,1.2, "cm"))
jak_usage_plot
ggsave(jak_usage_plot, file='jak_usage_plot.png', dpi=600, width = 8, height = 8)

jakil<-uc_jaks |> pivot_longer(cols = JAK1:TYK2, names_to = 'jak', values_to = 'presence')
jak_protein_usage<-jakil |> filter(presence >0) |> group_by(jaks, jak) |> tally()

jak_protein_usage_plot<-ggplot(jak_protein_usage, aes(x=jaks, y=n, fill=jak)) + 
  geom_bar(stat = "identity", position='fill')+
  theme_hc(base_size = 16)+
  #scale_fill_manual(values = c('JAK1'='#e1f7d5', 'JAK2'='#f6a6b2', 'JAK3'='#f7c297', 'TYK2'='#eecbff'))+  
  scale_fill_manual(values = c('#eecbff','#f7c297','#f6a6b2','#e1f7d5') ,limits=c('TYK2','JAK3','JAK2','JAK1') )+  
  #scale_fill_manual(values = c('JAK1'='#eecbff', 'JAK2'='#f7c297', 'JAK3'='#f6a6b2', 'TYK2'='#e1f7d5'))+  
  coord_flip()+
  scale_x_reverse()+
  ylab('Ratio of JAK proteins')+
  theme(plot.margin = margin(1,1,1.5,1.2, "cm"))+
  ylab('Ratio of JAK proteins')+ guides(fill=guide_legend(title="JAK"))
jak_protein_usage_plot
ggsave(jak_protein_usage_plot, file='jak_protein_usage_plot.png', dpi=600, width = 8, height = 8)

IL2_family_members<- c('IL2','IL7','IL15','TSLP')
IL2_downstream_jaks <-c('JAK1','JAK3')
IL6_family_members<- c('IL6','OSM')
IL6_downstream_jaks <-c('JAK1','JAK2','TYK2')
IFN_family_members <-c('IFNG')
IFN_downstream_jaks <-c('JAK1','JAK2','TYK2')
IL10_family_members<- c('IL10')
IL10_downstream_jaks <-c('JAK1','JAK2','TYK2')
IL3_family_members<- c('CSF2')
IL3_downstream_jaks <-c('JAK2')
IL12_family_members<- c('IL23A')
IL12_downstream_jaks <-c('JAK2','TYK2')
CCL2 <- c('CCL2')
CCL2_jaks <- c('JAK2')
CCL5<-c('CCL5')
CCL5_jaks <- c('JAK1','JAK2','JAK3')

UC_and_healthy_interactions<-comp |> filter(state == 'UC_inflamed_naive'|state == 'UC_inflamed_treated'|state == 'UC_noninflamed_treated'|state == 'healthy') |> 
  select(source,target) |> distinct()
jakil_UC_and_healthy<-jakil |> right_join(UC_and_healthy_interactions)

jak_ratio_table <- function(i, jak_list){
  total_interactions <- comp |> filter(state == 'UC_inflamed_naive'|state == 'UC_inflamed_treated'|state == 'UC_noninflamed_treated'|state == 'healthy') |> 
    select(source,target) |> distinct() |>  filter(source == paste0(i)) |> nrow()
  
  valid_interactions <-  comp |> filter(state == 'UC_inflamed_naive'|state == 'UC_inflamed_treated'|state == 'UC_noninflamed_treated'|state == 'healthy') |> 
    select(source,target) |> distinct() |>  filter(source == paste0(i))
  
  any_jak <- jakil_UC_and_healthy |> right_join(valid_interactions) |> 
    filter(presence ==1) |> 
    select(source,target) |> distinct() |> nrow()
  
  correct_jak<-jakil_UC_and_healthy |> right_join(valid_interactions) |> 
    filter(presence ==1) |> 
    filter(jak %in% jak_list) |>
    select(source,target) |> distinct() |> nrow()
  
  out <- data.frame(
    cytokine = paste0(i),
    JAK1 = length(intersect('JAK1', jak_list)),
    JAK2 = length(intersect('JAK2', jak_list)),
    JAK3 = length(intersect('JAK3', jak_list)),
    TYK2 = length(intersect('TYK2', jak_list)),
    number_of_interactions <- total_interactions,
    number_of_interactions_with_JAKs<-any_jak,
    number_of_interactions_with_correct_JAKs<-correct_jak,
    Ratio_of_interactions_using_correct_JAK<-correct_jak / number_of_interactions ,
    Ratio_of_JAK_interactions_using_correct_JAK<-correct_jak/number_of_interactions_with_JAKs
  )
  return(out)
}

testlist <- list('IL2'=IL2_downstream_jaks,
                 'IL7'=IL2_downstream_jaks,
                 'IL15'=IL2_downstream_jaks,
                 'TSLP'=IL2_downstream_jaks,
                 'IL6'=IL6_downstream_jaks,
                 'IL11'=IL6_downstream_jaks,
                 'IL27'=IL6_downstream_jaks,
                 'IL31'=IL6_downstream_jaks,
                 'LIF'=IL6_downstream_jaks,
                 'OSM'=IL6_downstream_jaks,
                 'IFNA'=IFN_downstream_jaks,
                 'IFNB'=IFN_downstream_jaks,
                 'IFNG'=IFN_downstream_jaks,
                 'IL10'=IL10_downstream_jaks,
                 'IL19'=IL10_downstream_jaks,
                 'IL20'=IL10_downstream_jaks,
                 'IL24'=IL10_downstream_jaks,
                 'IL26'=IL10_downstream_jaks,
                 'IL3'=IL3_downstream_jaks,
                 'IL5'=IL3_downstream_jaks,
                 'CSF2'=IL3_downstream_jaks,
                 'IL12A'=IL12_downstream_jaks,
                 'IL23A'=IL12_downstream_jaks
)

jak_results <- list()
for (i in seq_along(testlist)) {
  key <- names(testlist)[i]
  value <- testlist[[i]]
  out_table<-jak_ratio_table(key,value)
  jak_results[[paste0(key)]]<-out_table
}

results_table <- bind_rows(jak_results)

results_table<-results_table |> dplyr::rename(Cytokine=cytokine, 
                                              Number_of_interactions=`number_of_interactions....total_interactions`,
                                              Number_of_interactions_using_JAKs=`number_of_interactions_with_JAKs....any_jak`, 
                                              Number_of_interactions_using_correct_JAKs = `number_of_interactions_with_correct_JAKs....correct_jak`,
                                              Percentage_of_interactions_using_correct_JAK =`Ratio_of_interactions_using_correct_JAK....correct_jak.number_of_interactions`,
                                              Percentage_of_JAK_interactions_using_correct_JAK=`Ratio_of_JAK_interactions_using_correct_JAK....correct_jak.number_of_interactions_with_JAKs`)

results_table_filtered<-results_table |> filter(Number_of_interactions > 0)

library(gt)
library(gtsummary)
library(gtExtras)


jaktable<-results_table_filtered |> rename_all(function(x) gsub("_", " ", x)) |> arrange(-`Percentage of interactions using correct JAK`) |> 
  gt() |>
  cols_width(
    starts_with("Percentage") ~ px(600)
  ) |> 
  data_color(columns = JAK1, method = 'numeric', palette = c('white','#e1f7d5')) |> 
  data_color(columns = JAK2, method = 'numeric', palette = c('white','#f6a6b2')) |> 
  data_color(columns = JAK3, method = 'numeric', palette = c('white','#f7c297')) |> 
  data_color(columns = TYK2, method = 'numeric', palette = c('white','#eecbff')) |> 
  gt_plt_bar_pct("Percentage of interactions using correct JAK", labels = T, fill='#ADB828') |> 
  gt_plt_bar_pct("Percentage of JAK interactions using correct JAK", labels = T, fill = 'lightblue') 
jaktable
ggsave(jaktable, file='jaktable.png', dpi=600, width = 12, height = 8)

```

```{r}
#Fig5C
# rewiring files

naive_int <- testcci |> ungroup() |> select(source,target)

jak1i<-jakil |> filter(jak == 'JAK1' & presence == 1) |> ungroup() |> select(source,target)
naive_jak1i<-naive_int |> anti_join(jak1i)
jak2i<-jakil |> filter(jak == 'JAK2' & presence == 1) |> ungroup() |> select(source,target)
naive_jak2i<-naive_int |> anti_join(jak2i)
jak3i<-jakil |> filter(jak == 'JAK3' & presence == 1) |> ungroup() |> select(source,target)
naive_jak3i<-naive_int |> anti_join(jak3i)
tyk2i<-jakil |> filter(jak == 'TYK2' & presence == 1) |> ungroup() |> select(source,target)
naive_tyk2i<-naive_int |> anti_join(tyk2i)
write_tsv(naive_int, 'inflamed_naive_network.tsv')
write_tsv(naive_jak1i, 'inflamed_naive_network_jak1i.tsv')
write_tsv(naive_jak2i, 'inflamed_naive_network_jak2i.tsv')
write_tsv(naive_jak3i, 'inflamed_naive_network_jak3i.tsv')
write_tsv(naive_tyk2i, 'inflamed_naive_network_tyk2i.tsv')

#rewiring values calculated in cytoscape following the removal of interactions from the UC naive network predicted to be signalling through each JAK paralogue 

rew_jk1 <- read_csv('jak1_rewiring.csv')|> dplyr::select(name, `DyNet Rewiring (Dn-score)`, `Edge Count`) |> dplyr::rename(Dn = `DyNet Rewiring (Dn-score)`, degree = `Edge Count`)
rew_jk1$state <-'JAK1 inhibited'
rew_jk2 <- read_csv('jak2_rewiring.csv')|> dplyr::select(name, `DyNet Rewiring (Dn-score)`, `Edge Count`) |> dplyr::rename(Dn = `DyNet Rewiring (Dn-score)`, degree = `Edge Count`)
rew_jk2$state <-'JAK2 inhibited'
rew_jk3 <- read_csv('jak3_rewiring.csv')|> dplyr::select(name, `DyNet Rewiring (Dn-score)`, `Edge Count`) |> dplyr::rename(Dn = `DyNet Rewiring (Dn-score)`, degree = `Edge Count`)
rew_jk3$state <-'JAK3 inhibited'
rew_tk2 <- read_csv('tyk2_rewiring.csv')|> dplyr::select(name, `DyNet Rewiring (Dn-score)`, `Edge Count`) |> dplyr::rename(Dn = `DyNet Rewiring (Dn-score)`, degree = `Edge Count`)
rew_tk2$state <-'TYK2 inhibited'

rew_jak <- rbind(rew_jk1, rew_jk2, rew_jk3, rew_tk2) |> filter(Dn != 0)
toprew <- rew_jak |> arrange(desc(abs(Dn))) |> group_by(state) |> slice(1:10) |> pull(name) |> unique()

jakrew<-ggplot(rew_jak, aes(x = reorder(name, Dn), y = Dn, fill = state)) +
  scale_x_discrete(limits = rev(toprew))+
  geom_bar(stat='identity', position = 'dodge')+
  scale_fill_manual(values = c('JAK1 inhibited'='#e1f7d5', 'JAK2 inhibited'='#f6a6b2', 'JAK3 inhibited'='#f7c297', 'TYK2 inhibited'='#eecbff'))+  coord_flip()+
  facet_grid(~state)+
  xlab('Cytokine affected by drug treatment')+
  ylab('Rewiring compared to UC naive network')+
  labs(fill = 'state')+
  theme_hc(base_size = 18)
jakrew
```

```{r}
library(ggpubr)
# OpenTargets data downloaded from website, i.e.: https://platform.opentargets.org/disease/EFO_0000729/classic-associations
otnew <- read_tsv('T-EFO_0000729-associated-targets-01_02_2024-v23_12.tsv') |> select(symbol, globalScore, maxClinicalTrialPhase)
otnew <- otnew |> mutate(maxClinicalTrialPhase = case_when(
  maxClinicalTrialPhase == 1 ~ 'IV',
  maxClinicalTrialPhase == 0.75 ~ 'III',
  maxClinicalTrialPhase == 0.5 ~ 'II',
  maxClinicalTrialPhase == 0.25 ~ 'I',
  TRUE ~ as.character(maxClinicalTrialPhase)
))
otewnames <- otnew$symbol |> unique()

df <- comp |> filter(state == 'UC_inflamed_naive') 

#Supplementary Figure 3
net_ot <- df |> as_tbl_graph() |>activate(nodes) |> left_join(otnew, by =c('name'='symbol')) |> mutate(maxClinicalTrialPhase = case_when(
  is.na(maxClinicalTrialPhase) ~ 'No data',
  TRUE ~ as.character(maxClinicalTrialPhase)
),degree = centrality_degree(mode='all')) |> as_tibble()

degscorecorr<-net_ot |> mutate(labelname = case_when(
  degree >= 8 & globalScore > 0.25 ~ as.character(name),
  TRUE ~ as.character('')
)) |>  ggplot(aes(x = degree, y= globalScore))+
  geom_point()+
  geom_smooth(method='lm' , color="red", fill="grey90", se=TRUE) +
  geom_text_repel(aes(label = labelname), repel = T)+
  stat_cor(method = 'pearson', color = "red", geom = "label")+
  theme_hc(base_size = 18)
degscorecorr


#top opentargets score cytokines
net_ot_plot<-net_ot|> arrange(-globalScore) |> head(10) |> mutate(drugstatus = case_when(
  name == 'TNF' ~ 'UC drug exists',
  name == 'IL23A' ~ 'UC drug exists',
  TRUE ~ 'No drug'
))|> mutate(name = case_when(
  name == 'TNFSF15' ~ 'TL1A',
  TRUE ~ as.character(name)
))

#Fig6B
net_ot_plot2<-ggplot(net_ot_plot, aes(x=reorder(name, globalScore), y=globalScore)) +
  geom_segment( aes(x=reorder(name, globalScore), xend=reorder(name, globalScore), y=0, yend=globalScore), color="grey80") +
  geom_point(aes(shape=drugstatus),fill="lightblue", size=5) +
    scale_shape_manual(values = c('UC drug exists' = 21, 'No drug' =  24))+
  theme_light() +
  coord_flip() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  )+
  theme_hc(base_size = 18)+
  xlab('Cytokine')+
  ylab('OpenTargets globalScore')+
  labs(shape='')
net_ot_plot2

top_drug_names <- net_ot|> arrange(-globalScore) |> head(15) |> pull(name)|> unique()

# Fig6A
phase_net <- df |> as_tbl_graph() |>activate(nodes) |> left_join(otnew, by =c('name'='symbol')) |> mutate(degree = centrality_degree(mode='all'),btw = centrality_betweenness(), maxClinicalTrialPhase = case_when(
  is.na(maxClinicalTrialPhase) ~ 'No data',
  TRUE ~ as.character(maxClinicalTrialPhase)
), 
globalScore = replace_na(globalScore, 0),
labelName = ifelse(name %in% top_drug_names, name, '')) |> mutate(labelName = case_when(
  labelName == 'TNFSF15' ~ 'TL1A',
  TRUE ~ as.character(labelName)
)) |> 
  ggraph(layout='centrality', cent=globalScore) + 
  geom_edge_link(color = '#FE6100',arrow = arrow(type = "closed", length = unit(2, "mm")), start_cap = circle(5, 'mm'), end_cap = circle(5, "mm"), width =0.75, alpha = 0.3) +
  geom_node_point(aes(fill = globalScore,size = degree), shape=21, color ='black') +
  scale_fill_gradient(low = "white", high = 'lightblue') +
  scale_size_continuous(range = c(2, 14), breaks = c(10,30,50)) +
  geom_node_text(aes(label = labelName),size = 5,fontface = 'bold', repel = T,show.legend = F) +
  theme_graph()+
  theme(text = element_text(family = 'Helvetica'))+
  theme(legend.position = 'bottom')+
  labs(fill='OpenTargets globalScore')
phase_net
```

```{r}
# Supplementary figure 1
library(ggVennDiagram)

# cell type intersections
celltypenaive1 <- cellcompint |> filter(state == 'UC_inflamed_naive') |> pull(source_cell) 
celltypenaive2 <- cellcompint |> filter(state == 'UC_inflamed_naive') |> pull(target_cell) 
celltypenaive <- c(celltypenaive1,celltypenaive2) |> unique()

ct1 <- cellcompint |> filter(state == 'UC_inflamed_treated') |> pull(source_cell) 
ct2 <- cellcompint |> filter(state == 'UC_inflamed_treated') |> pull(target_cell) 
ct <- c(ct1,ct2) |> unique()

ch1 <- cellcompint |> filter(state == 'healthy') |> pull(source_cell) 
ch2 <- cellcompint |> filter(state == 'healthy') |> pull(target_cell) 
ch <- c(ch1,ch2) |> unique()

celltypes<-list(inflamed_naive = celltypenaive, inflamed_treated = ct, healthy = ch)
ggVennDiagram(celltypes)+ scale_fill_distiller(palette = "YlGn", direction = 1)+ guides(fill=guide_legend(title="Overlapping cell types"))

```

```{r}
autocrine_signalling_ratio <- function(instate){
cellcompint_uc_h <- cellcompint |>filter(state == paste0(instate))
ints <- cellcompint_uc_h$interaction |> unique()
results <- list()
for (i in ints){
  int_source <- cellcompint_uc_h |>filter(interaction == paste0(i)) |> pull(source_cell) |> unique() 
  int_target <- cellcompint_uc_h |>filter(interaction == paste0(i)) |> pull(target_cell) |> unique() 
  cells <- intersect(int_source,int_target)
  count <- length(intersect(int_source,int_target))
  out <- data.frame(
  int <- paste0(i),
   autocrine_count<- count)
  results[[paste0(i)]] <- out
}
autocrine_data <- bind_rows(results)
return(autocrine_data)
}

autocrine_naive<-autocrine_signalling_ratio('UC_inflamed_naive')
autocrine_inflamed<-autocrine_signalling_ratio('UC_inflamed_treated')
autocrine_noninflamed<-autocrine_signalling_ratio('UC_noninflamed_treated')
autocrine_healthy<-autocrine_signalling_ratio('healthy')

autocrine_naive$state <- 'UC_inflamed_naive'
autocrine_inflamed$state <- 'UC_inflamed_treated'
autocrine_noninflamed$state <- 'UC_noninflamed_treated'
autocrine_healthy$state <- 'healthy'

autocrine<-rbind(autocrine_naive, autocrine_inflamed, autocrine_noninflamed, autocrine_healthy)

autocrine_ridge<-ggplot(autocrine, aes(x = autocrine_count....count , y = state)) +
  geom_density_ridges(aes(fill=state), stat = "binline", binwidth = 1, scale = 0.95) + 
  scale_y_discrete(expand = c(0, 0)) +     
  scale_x_continuous(expand = c(0, 0)) +   
  coord_cartesian(clip = "off") + 
  theme_ridges(grid = FALSE)+xlab('Overlapping source and target cell types in cytokine-cytokine interactions')
autocrine_ridge
# ratios, interactions with 0 overlap (i.e. no autocrine signal):
# naive = 141/443 = 0.31 == 69
# treated = 107/321 = 0.33 == 67
# noninflamed_treated = 115/358=0.32 == 68
# healthy = 102/376 = 0.27 == 73
```
